edition = "2018"
unstable_features = true

blank_lines_upper_bound = 3
brace_style = "PreferSameLine"
combine_control_expr = true
comment_width = 100
fn_args_layout = "Tall"
fn_single_line = true
group_imports = "StdExternalCrate"
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
newline_style = "Native"
overflow_delimited_expr = true
trailing_comma = "Never"
use_field_init_shorthand = false
use_small_heuristics = "Max"
where_single_line = true
wrap_comments = true
