name: Build DEB (Ubuntu 20.04)

on: release

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build DEB
      run: |
        cargo install cargo-deb
        cargo deb
    - name: Upload DEB
      uses: actions/upload-artifact@v2
      with:
        name: "ubuntu-20.04"
        path: target/debian/*.deb
